# Generated by Django 4.2.7 on 2024-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
